import {
  PaginatedSolicitudListDto,
  SolicitudListItemDto,
  SolicitudStatus,
} from '@/dtos/solicitudes.dto';

const SOLICITUDES_LIST_SEED: SolicitudListItemDto[] = [
  {
    id: 'solicitud-pend-001',
    avatarUrl: 'https://i.pravatar.cc/96?img=5',
    tutorName: 'Carlos Ruiz',
    subject: 'Álgebra Lineal',
    dateTime: '2026-04-02T14:00:00.000Z',
    modality: 'Virtual',
    price: 8,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-001',
    avatarUrl: 'https://i.pravatar.cc/96?img=47',
    tutorName: 'María López',
    subject: 'Termodinámica',
    dateTime: '2026-02-01T10:00:00.000Z',
    modality: 'Virtual',
    price: 14,
    status: SolicitudStatus.EXPIRADA,
  },
  {
    id: 'solicitud-pend-002',
    avatarUrl: 'https://i.pravatar.cc/96?img=12',
    tutorName: 'David Gómez',
    subject: 'Dinámica',
    dateTime: '2026-04-12T16:00:00.000Z',
    modality: 'Presencial',
    price: 11,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-002',
    avatarUrl: 'https://i.pravatar.cc/96?img=15',
    tutorName: 'Ana Torres',
    subject: 'Cálculo Diferencial',
    dateTime: '2026-03-05T09:00:00.000Z',
    modality: 'Virtual',
    price: 10,
    status: SolicitudStatus.EXPIRADA,
  },
  {
    id: 'solicitud-pend-003',
    avatarUrl: 'https://i.pravatar.cc/96?img=20',
    tutorName: 'Juan Pérez',
    subject: 'Cálculo Vectorial',
    dateTime: '2026-04-06T14:00:00.000Z',
    modality: 'Presencial',
    price: 12,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-003',
    avatarUrl: 'https://i.pravatar.cc/96?img=25',
    tutorName: 'Sofía Martínez',
    subject: 'Programación I',
    dateTime: '2026-02-20T11:00:00.000Z',
    modality: 'Virtual',
    price: 13,
    status: SolicitudStatus.EXPIRADA,
  },
  {
    id: 'solicitud-pend-004',
    avatarUrl: 'https://i.pravatar.cc/96?img=33',
    tutorName: 'Laura Vélez',
    subject: 'Física II',
    dateTime: '2026-04-18T08:00:00.000Z',
    modality: 'Presencial',
    price: 15,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-004',
    avatarUrl: 'https://i.pravatar.cc/96?img=38',
    tutorName: 'Roberto Dávila',
    subject: 'Literatura Española',
    dateTime: '2026-02-12T10:30:00.000Z',
    modality: 'Virtual',
    price: 9,
    status: SolicitudStatus.EXPIRADA,
  },
  {
    id: 'solicitud-pend-005',
    avatarUrl: 'https://i.pravatar.cc/96?img=41',
    tutorName: 'Lucía Andrade',
    subject: 'Química Orgánica',
    dateTime: '2026-04-25T15:00:00.000Z',
    modality: 'Virtual',
    price: 16,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-005',
    avatarUrl: 'https://i.pravatar.cc/96?img=52',
    tutorName: 'Diego Salas',
    subject: 'Estadística',
    dateTime: '2026-02-15T13:30:00.000Z',
    modality: 'Presencial',
    price: 10,
    status: SolicitudStatus.EXPIRADA,
  },
  {
    id: 'solicitud-pend-006',
    avatarUrl: 'https://i.pravatar.cc/96?img=57',
    tutorName: 'Gabriela León',
    subject: 'Ecuaciones Diferenciales',
    dateTime: '2026-04-29T17:00:00.000Z',
    modality: 'Presencial',
    price: 12,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-006',
    avatarUrl: 'https://i.pravatar.cc/96?img=62',
    tutorName: 'Héctor Mora',
    subject: 'Economía',
    dateTime: '2026-02-28T09:30:00.000Z',
    modality: 'Virtual',
    price: 11,
    status: SolicitudStatus.EXPIRADA,
  },
  {
    id: 'solicitud-pend-007',
    avatarUrl: 'https://i.pravatar.cc/96?img=68',
    tutorName: 'Elena Paredes',
    subject: 'Matemática Discreta',
    dateTime: '2026-05-02T10:00:00.000Z',
    modality: 'Virtual',
    price: 9,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-007',
    avatarUrl: 'https://i.pravatar.cc/96?img=70',
    tutorName: 'Pablo Cárdenas',
    subject: 'Electrónica',
    dateTime: '2026-03-01T11:00:00.000Z',
    modality: 'Presencial',
    price: 14,
    status: SolicitudStatus.EXPIRADA,
  },
  {
    id: 'solicitud-pend-008',
    avatarUrl: 'https://i.pravatar.cc/96?img=72',
    tutorName: 'Fernanda Ruiz',
    subject: 'Bases de Datos',
    dateTime: '2026-05-05T18:00:00.000Z',
    modality: 'Presencial',
    price: 15,
    status: SolicitudStatus.PENDIENTE,
  },
  {
    id: 'solicitud-exp-008',
    avatarUrl: 'https://i.pravatar.cc/96?img=74',
    tutorName: 'Nicolás Bravo',
    subject: 'Redes',
    dateTime: '2026-03-02T16:00:00.000Z',
    modality: 'Virtual',
    price: 13,
    status: SolicitudStatus.EXPIRADA,
  },
];

export function getSolicitudesListSeed(): SolicitudListItemDto[] {
  return SOLICITUDES_LIST_SEED;
}

export function getPaginatedSolicitudesListSeed(page = 1, limit = 5): PaginatedSolicitudListDto {
  const safePage = Math.max(1, page);
  const safeLimit = Math.max(1, limit);
  const start = (safePage - 1) * safeLimit;
  const items = SOLICITUDES_LIST_SEED.slice(start, start + safeLimit);

  return {
    items,
    total: SOLICITUDES_LIST_SEED.length,
    page: safePage,
    limit: safeLimit,
  };
}
