import { Category } from '@/interfaces/oferta/Category';

export function getCategoriesSeed(): Category[] {
  return [
    { id: 'cat-001', name: 'Matemáticas' },
    { id: 'cat-002', name: 'Física' },
    { id: 'cat-003', name: 'Química' },
    { id: 'cat-004', name: 'Biología' },
    { id: 'cat-005', name: 'Programación' },
    { id: 'cat-006', name: 'Python' },
    { id: 'cat-007', name: 'JavaScript' },
    { id: 'cat-008', name: 'TypeScript' },
    { id: 'cat-009', name: 'React' },
    { id: 'cat-010', name: 'English' },
    { id: 'cat-011', name: 'Spanish' },
    { id: 'cat-012', name: 'French' },
    { id: 'cat-013', name: 'History' },
    { id: 'cat-014', name: 'Geography' },
    { id: 'cat-015', name: 'Economics' },
    { id: 'cat-016', name: 'Business' },
    { id: 'cat-017', name: 'Marketing' },
    { id: 'cat-018', name: 'Design' },
    { id: 'cat-019', name: 'Music' },
    { id: 'cat-020', name: 'Art' },
    { id: 'cat-021', name: 'Literature' },
    { id: 'cat-022', name: 'Philosophy' },
    { id: 'cat-023', name: 'Psychology' },
    { id: 'cat-024', name: 'Sociology' },
    { id: 'cat-025', name: 'Ciencias Exactas' },
    { id: 'cat-026', name: 'Cálculo' },
    { id: 'cat-027', name: 'Álgebra' },
    { id: 'cat-028', name: 'Geometría' },
    { id: 'cat-029', name: 'Estadística' },
    { id: 'cat-030', name: 'Programación Avanzada' },
    { id: 'cat-031', name: 'Formación Básica' },
    { id: 'cat-032', name: 'Preparación de Exámenes' },
    { id: 'cat-033', name: 'Resolución de Ejercicios' },
    { id: 'cat-034', name: 'Laboratorio' },
    { id: 'cat-035', name: 'FICA - Civil y Ambiental' },
    { id: 'cat-036', name: 'FIGP - Geología y Petróleos' },
    { id: 'cat-037', name: 'Mecánica' },
    { id: 'cat-038', name: 'Electricidad' },
    { id: 'cat-039', name: 'Electrónica' },
  ];
}
