import { PaginatedOffersResponse } from '@/interfaces/offers/OfferResponseDto';

export function getOffersSeedData(): PaginatedOffersResponse {
  return {
    data: [
      {
        id: '1',
        title: 'Cálculo Vectorial',
        price: 10,
        modality: 'Virtual/Presencial',
        description: 'Clases de Cálculo Vectorial para estudiantes de primeros semestres. Incluye integrales múltiples, campos vectoriales y...',
        tags: ['Matemática', 'Formación Básica'],
        rating: 4.8,
        reviewsCount: 15,
        tutor: {
          id: 'tutor-1',
          name: 'Juan Pérez',
          photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        },
      },
      {
        id: '2',
        title: 'Física I',
        price: 8,
        modality: 'Presencial',
        description: 'Tutoría de Física I: cinemática, dinámica, trabajo y energía. Resolución de problemas tipo examen.',
        tags: ['Física', 'Formación Médica'],
        rating: 4.0,
        reviewsCount: 12,
        tutor: {
          id: 'tutor-2',
          name: 'Juan Pérez',
          photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
        },
      },
      {
        id: '3',
        title: 'Estética',
        price: 12,
        modality: 'Virtual/Presencial',
        description: 'Apoyo estético de forma práctica: equilibrio de partículas, cuerpos rígidos, análisis de estructuras.',
        tags: ['Matemática', 'Ética y Valores'],
        rating: 4.8,
        reviewsCount: 8,
        tutor: {
          id: 'tutor-3',
          name: 'Juan Pérez',
          photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
        },
      },
      {
        id: '4',
        title: 'Programación Básica',
        price: 15,
        modality: 'Virtual',
        description: 'Clases de programación desde cero. Python, lógica de programación, estructuras de control y funciones.',
        tags: ['Programación', 'Formación Medios'],
        rating: 5,
        reviewsCount: 23,
        tutor: {
          id: 'tutor-4',
          name: 'María López',
          photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
        },
      },
      {
        id: '5',
        title: 'Ecuaciones Diferenciales',
        price: 9,
        modality: 'Presencial',
        description: 'Domina las ecuaciones diferenciales: EDO de primer y segundo orden, sistemas de ecuaciones, transformada de Laplace.',
        tags: ['Matemática', 'Sistemas de Ecuaciones'],
        rating: 4.5,
        reviewsCount: 18,
        tutor: {
          id: 'tutor-5',
          name: 'Carlos Ruiz',
          photo: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=400&h=400&fit=crop',
        },
      },
      {
        id: '6',
        title: 'Álgebra Lineal',
        price: 8,
        modality: 'Virtual/Presencial',
        description: 'Álgebra lineal completa: matrices, determinantes, espacios vectoriales, transformaciones lineales.',
        tags: ['Matemática', 'Formación Básica'],
        rating: 4.5,
        reviewsCount: 20,
        tutor: {
          id: 'tutor-6',
          name: 'Carlos Ruiz',
          photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        },
      },
      {
        id: '7',
        title: 'Química General',
        price: 10,
        modality: 'Presencial',
        description: 'Química general para ingenieros: estequiometría, equilibrio químico, termodinámica. Apoyo laboratorios.',
        tags: ['Química', 'Formación Básica'],
        rating: 4.9,
        reviewsCount: 30,
        tutor: {
          id: 'tutor-7',
          name: 'Ana Torres',
          photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
        },
      },
      {
        id: '8',
        title: 'Estética',
        price: 8,
        modality: 'Virtual/Presencial',
        description: 'Clases de estética enfocadas en ejercicios prácticos y preparación para exámenes.',
        tags: ['Matemática', 'Ética y Valores'],
        rating: 4.2,
        reviewsCount: 14,
        tutor: {
          id: 'tutor-8',
          name: 'David Gómez',
          photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
        },
      },
      {
        id: '9',
        title: 'Dinámica',
        price: 9,
        modality: 'Virtual',
        description: 'Dinámica de partículas y cuerpos rígidos. Cinemática, cinética, trabajo y energía. Enfoque en resolutor de ejercicios tipo examen.',
        tags: ['Matemática', 'Formación Medios'],
        rating: 4.2,
        reviewsCount: 11,
        tutor: {
          id: 'tutor-9',
          name: 'David Gómez',
          photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        },
      },
      {
        id: '10',
        title: 'Cálculo Diferencial',
        price: 10,
        modality: 'Virtual/Presencial',
        description: 'Límites, derivadas, aplicaciones de la derivada e optimización. Enfoque en resolutor de ejercicios tipo examen.',
        tags: ['Matemática', 'Métodos'],
        rating: 4.5,
        reviewsCount: 25,
        tutor: {
          id: 'tutor-10',
          name: 'Ana Torres',
          photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
        },
      },
      {
        id: '11',
        title: 'Métodos Numéricos',
        price: 12,
        modality: 'Virtual',
        description: 'Métodos numéricos aplicados: interpolación, resolución de ecuaciones, integración numérica.',
        tags: ['Matemática', 'Computación'],
        rating: 4.6,
        reviewsCount: 19,
        tutor: {
          id: 'tutor-11',
          name: 'Elena García',
          photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
        },
      },
      {
        id: '12',
        title: 'Termodinámica',
        price: 11,
        modality: 'Presencial',
        description: 'Principios de termodinámica aplicados a la ingeniería: ciclos, trabajo, calor y entropía.',
        tags: ['Física', 'Ingeniera Mecánica'],
        rating: 4.7,
        reviewsCount: 16,
        tutor: {
          id: 'tutor-12',
          name: 'Roberto Sánchez',
          photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
        },
      },
      {
        id: '13',
        title: 'Teoría de Grafos',
        price: 13,
        modality: 'Virtual/Presencial',
        description: 'Teoría de grafos: conceptos básicos, algoritmos de búsqueda, caminos más cortos y aplicaciones.',
        tags: ['Matemática Discreta', 'Algorítmica'],
        rating: 4.9,
        reviewsCount: 22,
        tutor: {
          id: 'tutor-13',
          name: 'Sofía Martínez',
          photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
        },
      },
    ],
    meta: {
      totalResults: 13,
      currentPage: 1,
      itemsPerPage: 10,
      totalPages: 2,
    },
  };
}
