import { PaginatedSolicitudesDto } from '@/interfaces/solicitudes/SolicitudesDTO';

export const paginatedSolicitudesExpiredSeed: PaginatedSolicitudesDto = {
  data: [
    {
      id: 'sol-exp-001',
      estudiante: 'Diego Castillo',
      materia: 'Fisica I',
      fechaHora: '20 ene 2026 · 14:00',
      mensajeResumen: 'Necesitaba ayuda con cinematica pero ya paso la fecha...',
      estado: 'EXPIRADA',
      modalidad: 'Presencial',
      precioHora: 8,
      mensajeCompleto: 'Necesitaba ayuda con cinematica pero ya paso la fecha.',
    },
    {
      id: 'sol-exp-002',
      estudiante: 'Andres Morales',
      materia: 'Calculo Vectorial',
      fechaHora: '6 mar 2026 · 14:00',
      mensajeResumen: 'Hola Joan, necesito ayuda con integrales de linea y superficies...',
      estado: 'EXPIRADA',
      modalidad: 'Virtual',
      precioHora: 12,
      mensajeCompleto:
        'Hola Joan, necesito ayuda con integrales de linea y superficies. Tengo examen esta semana y no entiendo los conceptos clave.',
    },
    {
      id: 'sol-exp-003',
      estudiante: 'Mateo Vargas',
      materia: 'Calculo Vectorial',
      fechaHora: '6 mar 2026 · 16:00',
      mensajeResumen: 'Hola, necesito reforzar series de Taylor y convergencia...',
      estado: 'EXPIRADA',
      modalidad: 'Virtual',
      precioHora: 11,
      mensajeCompleto:
        'Hola, necesito reforzar series de Taylor y convergencia. Mi examen es este viernes.',
    },
    {
      id: 'sol-exp-004',
      estudiante: 'Sofia Mendoza',
      materia: 'Algebra Lineal',
      fechaHora: '7 mar 2026 · 10:00',
      mensajeResumen: 'Necesito ayuda con transformaciones lineales y espacios vectoriales...',
      estado: 'EXPIRADA',
      modalidad: 'Presencial',
      precioHora: 10,
      mensajeCompleto:
        'Necesito ayuda con transformaciones lineales y espacios vectoriales. Tengo el parcial esta semana.',
    },
    {
      id: 'sol-exp-005',
      estudiante: 'Camila Flores',
      materia: 'Fisica I',
      fechaHora: '7 mar 2026 · 11:00',
      mensajeResumen: 'Tengo problemas con oscilaciones y ondas. Necesito entender movimiento...',
      estado: 'EXPIRADA',
      modalidad: 'Virtual',
      precioHora: 9,
      mensajeCompleto:
        'Tengo problemas con oscilaciones y ondas. Necesito entender movimiento armonico simple antes del examen.',
    },
    {
      id: 'sol-exp-006',
      estudiante: 'Sebastian Rios',
      materia: 'Calculo Vectorial',
      fechaHora: '7 mar 2026 · 13:00',
      mensajeResumen: 'Necesito repasar integrales dobles y triples. Tengo dificultades...',
      estado: 'EXPIRADA',
      modalidad: 'Presencial',
      precioHora: 8,
      mensajeCompleto:
        'Necesito repasar integrales dobles y triples. Tengo dificultades con el cambio de variables y coordenadas.',
    },
    {
      id: 'sol-exp-007',
      estudiante: 'Valeria Sanchez',
      materia: 'Fisica I',
      fechaHora: '7 mar 2026 · 15:00',
      mensajeResumen: 'Necesito repasar cinematica y dinamica para el parcial...',
      estado: 'EXPIRADA',
      modalidad: 'Virtual',
      precioHora: 10,
      mensajeCompleto:
        'Necesito repasar cinematica y dinamica para el parcial. Especificamente movimiento circular y trabajo-energia.',
    },
    {
      id: 'sol-exp-008',
      estudiante: 'Valeria Sanchez',
      materia: 'Calculo Vectorial',
      fechaHora: '8 mar 2026 · 09:00',
      mensajeResumen: 'Necesito repasar el teorema de la divergencia y aplicaciones...',
      estado: 'EXPIRADA',
      modalidad: 'Virtual',
      precioHora: 11,
      mensajeCompleto: 'Necesito repasar el teorema de la divergencia y aplicaciones de integrales triples.',
    },
    {
      id: 'sol-exp-009',
      estudiante: 'Lucas Herrera',
      materia: 'Algebra Lineal',
      fechaHora: '8 mar 2026 · 10:00',
      mensajeResumen: 'Necesito entender descomposicion LU y valores propios...',
      estado: 'EXPIRADA',
      modalidad: 'Presencial',
      precioHora: 10,
      mensajeCompleto:
        'Necesito entender descomposicion LU y valores propios. Tengo un proyecto de machine learning que los requiere.',
    },
    {
      id: 'sol-exp-010',
      estudiante: 'Diego Castillo',
      materia: 'Estatica',
      fechaHora: '8 mar 2026 · 11:00',
      mensajeResumen: 'Tengo dudas sobre el metodo de secciones para armaduras...',
      estado: 'EXPIRADA',
      modalidad: 'Presencial',
      precioHora: 8,
      mensajeCompleto: 'Tengo dudas sobre el metodo de secciones para armaduras. El examen es el lunes.',
    },
  ],
  total: 14,
  page: 1,
  limit: 10,
};
