import { HistoryResponse, TutorialDetailDto, TutorialHistoryItemDto } from '@/interfaces/tutorial/tutorial';

const historyItemsSeed: TutorialHistoryItemDto[] = [
  {
    id: 'tutoria-001-abc',
    studentInitials: 'MV',
    studentName: 'Mateo Vargas',
    offerTitle: 'Calculo Vectorial',
    date: '22 de marzo de 2026',
    time: '09:00',
    status: 'Completada',
  },
  {
    id: 'tutoria-002-def',
    studentInitials: 'CR',
    studentName: 'Camila Rodriguez',
    offerTitle: 'Calculo Vectorial',
    date: '21 de marzo de 2026',
    time: '10:00',
    status: 'Inasistencia',
  },
  {
    id: 'tutoria-003-ghi',
    studentInitials: 'AM',
    studentName: 'Andres Morales',
    offerTitle: 'Algebra Lineal',
    date: '20 de marzo de 2026',
    time: '11:00',
    status: 'Completada',
  },
  {
    id: 'tutoria-004-jkl',
    studentInitials: 'AM',
    studentName: 'Andres Morales',
    offerTitle: 'Calculo Vectorial',
    date: '15 de marzo de 2026',
    time: '10:00',
    status: 'Completada',
  },
  {
    id: 'tutoria-005-mno',
    studentInitials: 'SR',
    studentName: 'Sebastian Rios',
    offerTitle: 'Calculo Vectorial',
    date: '8 de marzo de 2026',
    time: '09:00',
    status: 'Completada',
  },
  {
    id: 'tutoria-006-pqr',
    studentInitials: 'JP',
    studentName: 'Juliana Paz',
    offerTitle: 'Programacion Orientada a Objetos',
    date: '2 de marzo de 2026',
    time: '14:30',
    status: 'Completada',
  },
  {
    id: 'tutoria-007-stu',
    studentInitials: 'DL',
    studentName: 'Diego Luna',
    offerTitle: 'Fisica I',
    date: '25 de febrero de 2026',
    time: '16:00',
    status: 'Completada',
  },
  {
    id: 'tutoria-008-vwx',
    studentInitials: 'NG',
    studentName: 'Nadia Guerrero',
    offerTitle: 'Algebra Lineal',
    date: '18 de febrero de 2026',
    time: '08:30',
    status: 'Inasistencia',
  },
  {
    id: 'tutoria-009-yza',
    studentInitials: 'FA',
    studentName: 'Fabian Acosta',
    offerTitle: 'Calculo Diferencial',
    date: '9 de febrero de 2026',
    time: '12:00',
    status: 'Completada',
  },
  {
    id: 'tutoria-010-bcd',
    studentInitials: 'LV',
    studentName: 'Lucia Vega',
    offerTitle: 'Bases de Datos',
    date: '3 de febrero de 2026',
    time: '18:00',
    status: 'Completada',
  },
  {
    id: 'tutoria-011-efg',
    studentInitials: 'RD',
    studentName: 'Rocio Diaz',
    offerTitle: 'Matematica Discreta',
    date: '27 de enero de 2026',
    time: '09:30',
    status: 'Completada',
  },
  {
    id: 'tutoria-012-hij',
    studentInitials: 'PM',
    studentName: 'Pablo Mena',
    offerTitle: 'Programacion I',
    date: '15 de enero de 2026',
    time: '11:15',
    status: 'Completada',
  },
];

export const historySeedData: HistoryResponse = {
  summary: {
    completedTutorials: 9,
    subjectsTaught: 4,
    studentsQualified: 89,
  },
  paginatedData: {
    items: historyItemsSeed,
    total: historyItemsSeed.length,
    page: 1,
    limit: 5,
  },
};

export const tutorialDetailSeedData: TutorialDetailDto = {
  id: 'tutoria-001-abc',
  studentName: 'Mateo Vargas',
  studentInitials: 'MV',
  offerTitle: 'Calculo Vectorial',
  subject: 'Calculo Vectorial',
  date: '22 de marzo de 2026',
  time: '09:00',
  modality: 'Presencial',
  price: 10,
  currency: 'USD',
  locationOrLink: 'Biblioteca EPN, Sala 3',
  message: 'Repaso general para el examen final.',
  status: 'Completada',
};
