import type { TutoriaDetalleDTO } from '@/interfaces/historial/HistorialTypes';

const tutoriaDetalleSeedData: TutoriaDetalleDTO[] = [
  {
    id: 'hist-001',
    materia: 'Programación Orientada a Objetos',
    tutor: {
      id: 'tutor-001',
      nombre: 'María',
      apellido: 'López',
      fotoUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    },
    fecha: '2026-03-05T14:00:00.000Z',
    hora: '14:00',
    modalidad: 'Virtual',
    precioPorHora: 12.00,
    enlaceReunion: 'https://zoom.us/j/9876543210',
    ubicacion: null,
    mensajeEstudiante: 'Necesito ayuda con los patrones de diseño.',
    estado: 'COMPLETADA',
  },
  {
    id: 'hist-002',
    materia: 'Física II',
    tutor: {
      id: 'tutor-002',
      nombre: 'Carlos',
      apellido: 'Ruiz',
      fotoUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
    },
    fecha: '2026-02-22T10:00:00.000Z',
    hora: '10:00',
    modalidad: 'Virtual',
    precioPorHora: 9.00,
    enlaceReunion: null,
    ubicacion: null,
    mensajeEstudiante: 'Repaso de electromagnetismo.',
    estado: 'INASISTENCIA',
  },
  {
    id: 'hist-003',
    materia: 'Cálculo Diferencial',
    tutor: {
      id: 'tutor-003',
      nombre: 'Juan',
      apellido: 'Pérez',
      fotoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    fecha: '2026-02-25T11:00:00.000Z',
    hora: '11:00',
    modalidad: 'Presencial',
    precioPorHora: 10.00,
    enlaceReunion: null,
    ubicacion: 'Biblioteca Central, Sala 3',
    mensajeEstudiante: 'Dudas con integrales indefinidas.',
    estado: 'COMPLETADA',
  },
  {
    id: 'hist-004',
    materia: 'Álgebra Lineal',
    tutor: {
      id: 'tutor-003',
      nombre: 'Juan',
      apellido: 'Pérez',
      fotoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    fecha: '2026-01-20T15:00:00.000Z',
    hora: '15:00',
    modalidad: 'Virtual',
    precioPorHora: 10.00,
    enlaceReunion: null,
    ubicacion: null,
    mensajeEstudiante: 'Repaso de vectores y matrices.',
    estado: 'INASISTENCIA',
  },
  {
    id: 'hist-005',
    materia: 'Estructuras de Datos',
    tutor: {
      id: 'tutor-001',
      nombre: 'María',
      apellido: 'López',
      fotoUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    },
    fecha: '2026-02-20T14:00:00.000Z',
    hora: '14:00',
    modalidad: 'Virtual',
    precioPorHora: 11.00,
    enlaceReunion: 'https://meet.google.com/abc-def-ghi',
    ubicacion: null,
    mensajeEstudiante: 'Ayuda con árboles binarios de búsqueda.',
    estado: 'COMPLETADA',
  },
  {
    id: 'hist-006',
    materia: 'Dinámica',
    tutor: {
      id: 'tutor-004',
      nombre: 'David',
      apellido: 'Gómez',
      fotoUrl: 'https://randomuser.me/api/portraits/men/62.jpg',
    },
    fecha: '2026-03-01T10:00:00.000Z',
    hora: '10:00',
    modalidad: 'Presencial',
    precioPorHora: 10.00,
    enlaceReunion: null,
    ubicacion: 'Facultad de Ingeniería, Aula B-204',
    mensajeEstudiante: 'Practicar problemas de energía y momento angular.',
    estado: 'COMPLETADA',
  },
  {
    id: 'hist-007',
    materia: 'Estática',
    tutor: {
      id: 'tutor-003',
      nombre: 'Juan',
      apellido: 'Pérez',
      fotoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    fecha: '2026-02-15T10:00:00.000Z',
    hora: '10:00',
    modalidad: 'Virtual',
    precioPorHora: 8.00,
    enlaceReunion: null,
    ubicacion: null,
    mensajeEstudiante: 'Repaso de cinemática y dinámica.',
    estado: 'COMPLETADA',
  },
  {
    id: 'hist-008',
    materia: 'Física I',
    tutor: {
      id: 'tutor-003',
      nombre: 'Juan',
      apellido: 'Pérez',
      fotoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    fecha: '2026-01-25T15:00:00.000Z',
    hora: '15:00',
    modalidad: 'Virtual',
    precioPorHora: 8.00,
    enlaceReunion: null,
    ubicacion: null,
    mensajeEstudiante: 'Repaso de cinemática y dinámica.',
    estado: 'COMPLETADA',
  },
  {
    id: 'hist-009',
    materia: 'Ecuaciones Diferenciales',
    tutor: {
      id: 'tutor-002',
      nombre: 'Carlos',
      apellido: 'Ruiz',
      fotoUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
    },
    fecha: '2026-01-25T10:00:00.000Z',
    hora: '10:00',
    modalidad: 'Presencial',
    precioPorHora: 9.00,
    enlaceReunion: null,
    ubicacion: 'Aula 305',
    mensajeEstudiante: 'Dudas con ecuaciones de segundo orden.',
    estado: 'INASISTENCIA',
  },
  {
    id: 'hist-010',
    materia: 'Química Orgánica',
    tutor: {
      id: 'tutor-005',
      nombre: 'Ana',
      apellido: 'Torres',
      fotoUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    },
    fecha: '2026-02-28T11:00:00.000Z',
    hora: '11:00',
    modalidad: 'Virtual',
    precioPorHora: 10.00,
    enlaceReunion: 'https://zoom.us/j/1112223334',
    ubicacion: null,
    mensajeEstudiante: 'Reacciones de sustitución nucleofílica.',
    estado: 'COMPLETADA',
  },
];

export function getTutoriaDetalleSeedData(tutoriaId: string): TutoriaDetalleDTO | undefined {
  return tutoriaDetalleSeedData.find((t) => t.id === tutoriaId);
}
